spring:
    application:
        name: management
    datasource:
        url: jdbc:postgresql://localhost:5432/management
        username: postgres
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    level:
        org:
            springframework:
                security: DEBUG
                web: DEBUG
                security.web.authentication: DEBUG
                security.web.authentication.UsernamePasswordAuthenticationFilter: DEBUG
